/**
 * Mock data for Luxe Foods - used when Supabase is not configured.
 * Real food images from Unsplash (free to use).
 */

import type { Category, MenuItem, MenuItemSize, MenuItemOption } from "./types"

const now = new Date().toISOString()
const img = (id: string) => `https://images.unsplash.com/photo-${id}?w=600&q=80`

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Breakfast",
    slug: "breakfast",
    description: "Start your day right",
    image_url: img("1504674900247-0877df9cc836"),
    sort_order: 1,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-2",
    name: "Main Dishes",
    slug: "main-dishes",
    description: "Hearty meals",
    image_url: img("1567620905731-2be74781c42b"),
    sort_order: 2,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-3",
    name: "Drinks",
    slug: "drinks",
    description: "Refreshments",
    image_url: img("1621506283937-042d5ff704aa"),
    sort_order: 3,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-4",
    name: "Pastries & Snacks",
    slug: "pastries-snacks",
    description: "Sweet and savoury",
    image_url: img("1555507036-ab1f4038808a"),
    sort_order: 4,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
]

export const MOCK_MENU_ITEMS: (MenuItem & { sizes?: MenuItemSize[]; options?: MenuItemOption[] })[] = [
  {
    id: "item-1",
    category_id: "cat-1",
    name: "Full English Breakfast",
    description: "Eggs, bacon, sausage, beans, toast and tomatoes",
    price: 45,
    image_url: img("1504674900247-0877df9cc836"),
    is_available: true,
    is_popular: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
    sizes: [
      { id: "size-1a", menu_item_id: "item-1", size_name: "Regular", price: 45, is_default: true, created_at: now },
      { id: "size-1b", menu_item_id: "item-1", size_name: "Large", price: 55, is_default: false, created_at: now },
    ],
    options: [],
  },
  {
    id: "item-2",
    category_id: "cat-1",
    name: "Pancakes with Syrup",
    description: "Fluffy pancakes with maple syrup and butter",
    price: 35,
    image_url: img("1567620905731-2be74781c42b"),
    is_available: true,
    is_popular: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
    sizes: [],
    options: [
      { id: "opt-2a", menu_item_id: "item-2", option_name: "Extra syrup", price_adjustment: 5, is_available: true, sort_order: 1, created_at: now },
    ],
  },
  {
    id: "item-3",
    category_id: "cat-2",
    name: "Jollof Rice",
    description: "Spiced rice with tomato and peppers, served with chicken",
    price: 50,
    image_url: img("1585937421612-70a008356fbe"),
    is_available: true,
    is_popular: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
    sizes: [
      { id: "size-3a", menu_item_id: "item-3", size_name: "Regular", price: 50, is_default: true, created_at: now },
      { id: "size-3b", menu_item_id: "item-3", size_name: "Large", price: 65, is_default: false, created_at: now },
    ],
    options: [],
  },
  {
    id: "item-4",
    category_id: "cat-2",
    name: "Fried Rice",
    description: "Stir-fried rice with vegetables and your choice of protein",
    price: 48,
    image_url: img("1603133872878-684f208fb84b"),
    is_available: true,
    is_popular: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
    sizes: [
      { id: "size-4a", menu_item_id: "item-4", size_name: "Regular", price: 48, is_default: true, created_at: now },
      { id: "size-4b", menu_item_id: "item-4", size_name: "Large", price: 60, is_default: false, created_at: now },
    ],
    options: [],
  },
  {
    id: "item-5",
    category_id: "cat-2",
    name: "Grilled Chicken",
    description: "Marinated grilled chicken with sides",
    price: 55,
    image_url: img("1598103442097-8b74394b95c6"),
    is_available: true,
    is_popular: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
    sizes: [],
    options: [],
  },
  {
    id: "item-6",
    category_id: "cat-3",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 15,
    image_url: img("1621506283937-042d5ff704aa"),
    is_available: true,
    is_popular: false,
    sort_order: 1,
    created_at: now,
    updated_at: now,
    sizes: [
      { id: "size-6a", menu_item_id: "item-6", size_name: "Small", price: 15, is_default: true, created_at: now },
      { id: "size-6b", menu_item_id: "item-6", size_name: "Large", price: 22, is_default: false, created_at: now },
    ],
    options: [],
  },
  {
    id: "item-7",
    category_id: "cat-3",
    name: "Soft Drink",
    description: "Coca-Cola, Fanta or Sprite",
    price: 10,
    image_url: img("1622483767028-3f66f32aef97"),
    is_available: true,
    is_popular: false,
    sort_order: 2,
    created_at: now,
    updated_at: now,
    sizes: [],
    options: [],
  },
  {
    id: "item-8",
    category_id: "cat-4",
    name: "Croissant",
    description: "Buttery French croissant",
    price: 18,
    image_url: img("1555507036-ab1f4038808a"),
    is_available: true,
    is_popular: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
    sizes: [],
    options: [],
  },
  {
    id: "item-9",
    category_id: "cat-4",
    name: "Chocolate Cake Slice",
    description: "Rich chocolate cake slice",
    price: 25,
    image_url: img("1578985545062-69928b1d9587"),
    is_available: true,
    is_popular: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
    sizes: [],
    options: [],
  },
]
